# Generated by Django 4.2.16 on 2024-11-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="code",
            name="category",
        ),
    ]
