# Generated by Django 4.2.16 on 2024-11-24 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0002_category_remove_code_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="snippet.category",
                verbose_name="カテゴリー",
            ),
            preserve_default=False,
        ),
    ]
