# Generated by Django 4.2.16 on 2024-11-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0003_code_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="タグ")),
            ],
        ),
        migrations.AddField(
            model_name="code",
            name="relation",
            field=models.ManyToManyField(
                blank=True, null=True, to="snippet.code", verbose_name="関連"
            ),
        ),
        migrations.AddField(
            model_name="code",
            name="tag",
            field=models.ManyToManyField(to="snippet.tag", verbose_name="タグ"),
        ),
    ]
