# Generated by Django 5.1.3 on 2024-11-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0004_tag_code_relation_code_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="snippet.category",
                verbose_name="カテゴリー",
            ),
        ),
        migrations.AlterField(
            model_name="code",
            name="code",
            field=models.TextField(verbose_name="コード"),
        ),
        migrations.AlterField(
            model_name="code",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
        ),
        migrations.AlterField(
            model_name="code",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="メモ"),
        ),
        migrations.AlterField(
            model_name="code",
            name="tag",
            field=models.ManyToManyField(
                blank=True, null=True, to="snippet.tag", verbose_name="タグ"
            ),
        ),
        migrations.AlterField(
            model_name="code",
            name="title",
            field=models.CharField(max_length=200, verbose_name="タイトル"),
        ),
        migrations.AlterField(
            model_name="code",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日"),
        ),
    ]
