# Generated by Django 5.1.3 on 2024-11-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0005_alter_code_category_alter_code_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="snippet.tag", verbose_name="タグ"
            ),
        ),
    ]
