# Generated by Django 5.1.3 on 2024-11-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0008_alter_userprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="favorite_code",
            new_name="favorite_codes",
        ),
    ]
